import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

// Preact 兼容层别名：运行时把 react* / react-dom* 重定向到 preact/compat，
// jsx-runtime 重定向到 preact。类型仍由 @types/react 提供（tsc -noEmit）。
const preactAlias = {
  name: "preact-alias",
  setup(build) {
    const map = {
      react: "preact/compat",
      "react-dom": "preact/compat",
      "react-dom/client": "preact/compat/client",
      "react/jsx-runtime": "preact/jsx-runtime",
    };
    for (const [from, to] of Object.entries(map)) {
      const filter = new RegExp(
        "^" + from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "$",
      );
      build.onResolve({ filter }, () => ({ path: require.resolve(to) }));
    }
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [preactAlias],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  loader: { ".tsx": "tsx", ".ts": "ts" },
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  define: { "process.env.NODE_ENV": prod ? '"production"' : '"development"' },
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
